name: Java CI with Maven

on:
  push:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn verify
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: jar
          path: target/*.jar

  createDocker:
    services:
      docker:
        image: docker:latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          name: jar
          path: target/*.jar
      - name: Build Docker
        run: docker build -t ghcr.io/fakugithub/devopsbeispielGH .
      - name: Login to Docker
        run: docker login ghcr.io --username ${{ DOCKER_TOKEN }} --password ${{ DOCKER_TOKEN }}
      - name: Push to Docker
        run: docker push ghcr.io/fakugithub/devopsbeispielGH
